### ISSUE TITLE
fitted-heading -otsikot ei saatanoidu

### ISSUE THREAD

**Issue by kallioaleksi** [veeti/iltasaatana#1]
Isoimmat otsikot ei saatanoidu saatana.

Ilmeisesti pitäisi hakea fitted-heading -classin lapsista viimeinen ja muokata/lisätä tähän saatana.

**Comment by veeti** [comment]
Ilta-Sanomat vähän päivitteli ulkoasua enkä jaksanut vielä korjata. Pistin nyt päivityksen.
